### ISSUE TITLE
Star Rating not updating on ng-repeat 

### ISSUE THREAD

**Issue by swapnilaryan** [juank11memphis/angular-jk-rating-stars#18]
I am using jk-rating-stars for star rating for my website. When the page is loaded all the ratings made by a user is available via ng-repeat. 

Now when a new comment is posted then all the previous rating goes grey (null). But on refresh evrything shows correctly. 

Any solutions might help..!!

**Comment by juank11memphis** [comment]
Fixed with https://github.com/juank11memphis/angular-jk-rating-stars/pull/19
